version: "3.4"

services:
  modcidadao_db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "Postgres2021!"
    ports: 
      - 15433:5432
    volumes: 
      - C:\postgres\dbmodcidadao:/var/lib/postgresql/data

  modintegracao_zookeeper:
    image: confluentinc/cp-zookeeper
    ports: 
      - "2181:2181"
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181

  modintegracao_kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - modintegracao_zookeeper
    ports: 
      - "9092:9092"
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: modintegracao_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.15.200:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      PRODUCER_ACKS: all
      