version: "3.4"

services:  
  stur:
    image: testeapi-image
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "6030:8090"
    environment: 
      ASPNETCORE_ENVIRONMENT: Development            