version: "3.4"

services:  
  modintegracao_zookeeper:
    image: confluentinc/cp-zookeeper
    ports: 
      - "2181:2181"
    volumes: 
      - C:\sgmdata\zookeeper:/var/lib/zookeeper
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181

  modintegracao_kafka:
    image: confluentinc/cp-kafka
    depends_on: 
      - modintegracao_zookeeper
    ports: 
      - "9092:9092"
      - "19092:19092"
      - "29092:29092"
    volumes: 
      - C:\sgmdata\kafka:/var/lib/kafka
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: modintegracao_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://modintegracao_kafka:9092,LST1://localhost:19092,LST2://192.168.15.200:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LST1:PLAINTEXT,LST2:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      PRODUCER_ACKS: all


